eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka/
server:
  port: 9092

spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/chrywhy/test
          searchPaths: spring-cloud/helloworldConfig
  application:
    name: config