eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka/
server:
  port: 9092
spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wodkm/springCloudTest-config
          searchPaths:
          username:
          password:
  application:
    name: config