eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka/
server:
  port: 9091
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  application:
    name: web
  cloud:
    config:
      label: master
      profile: dev
      uri: http://127.0.0.1:9092/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**